language: bash

services:
  - docker

env:
  matrix:
  - KIBANA_VER=7.5.1 TAGS=7.5,7,latest
  - KIBANA_VER=6.8.5 TAGS=6.8,6

script:
- travis_retry make
- make test

after_success:
- . "${TRAVIS_BUILD_DIR}/release.sh"

notifications:
  email:
    recipients:
    - travisci@wodby.com
    on_success: never
    on_failure: always
